agolo-service:
  nameOverride: authentication-service
  replicas: 1
  image:
    repository: agolo.azurecr.io/service/authentication-service
    tag: prod

  envStrings:
    SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    ACCESS_TOKEN_VALID_INTERNAL: '3600000'
    REFRESH_TOKEN_VALID_INTERVAL: '86400000'

  network:
    type: ClusterIP
    ports:
      - name: http
        containerPort: 8080
        exposedPort: 8080
        ingresses:
          - host: authentication.prod.agolo.com
            path: /
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "200M"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "10000"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "10000"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "10000"